# Generated by Django 4.0.3 on 2022-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_col', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
    ]
