# Generated by Django 4.0.3 on 2022-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_col', models.CharField(max_length=100, verbose_name='Distance')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_col', models.CharField(max_length=100, verbose_name='Quantity')),
            ],
        ),
        migrations.RenameModel(
            old_name='Data',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='data_col',
            new_name='date_col',
        ),
    ]
