# Generated by Django 4.0.3 on 2022-03-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_distance_quantity_rename_data_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='bundle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='table.date'),
            preserve_default=False,
        ),
    ]
