# Generated by Django 4.0.3 on 2022-03-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_remove_name_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='bundle',
            field=models.ForeignKey(default=-18000, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='table.date'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_col',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
