# Generated by Django 4.0.3 on 2022-03-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_name_bundle_alter_date_date_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='bundle',
            field=models.ForeignKey(default=-18000, on_delete=django.db.models.deletion.CASCADE, related_name='dis', to='table.date'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='bundle',
            field=models.ForeignKey(default=-18000, on_delete=django.db.models.deletion.CASCADE, related_name='qua', to='table.date'),
        ),
    ]
